// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsWo31cfdMp7ey7TnPNH1w6lOQ-PLGM1Y',
    appId: '1:295701490748:web:b6729a79096129d87aa739',
    messagingSenderId: '295701490748',
    projectId: 'checkme-a0847',
    authDomain: 'checkme-a0847.firebaseapp.com',
    storageBucket: 'checkme-a0847.appspot.com',
    measurementId: 'G-SR8Q0P6Z48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr9qc5EftpsBSO6uOoPV9ww_Fd8ZohPmI',
    appId: '1:295701490748:android:5cf52ec6931099527aa739',
    messagingSenderId: '295701490748',
    projectId: 'checkme-a0847',
    storageBucket: 'checkme-a0847.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQtMZuGQYr0BTbCv7zFT0nezzL9yKmJ30',
    appId: '1:295701490748:ios:c2115a04942b10307aa739',
    messagingSenderId: '295701490748',
    projectId: 'checkme-a0847',
    storageBucket: 'checkme-a0847.appspot.com',
    iosBundleId: 'com.example.checkme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQtMZuGQYr0BTbCv7zFT0nezzL9yKmJ30',
    appId: '1:295701490748:ios:7703dcd4869d97e07aa739',
    messagingSenderId: '295701490748',
    projectId: 'checkme-a0847',
    storageBucket: 'checkme-a0847.appspot.com',
    iosBundleId: 'com.example.checkme.RunnerTests',
  );
}
